import { Component, OnInit } from '@angular/core';
import { EmptyTemplateService } from './modules/shared/services/empty-template.service';

@Component({
  selector: 'app-component-dev',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponentDev implements OnInit {

  injectedTemplate = {
    "@id": "https://repo.metadatacenter.orgx/templates/593922fe-d916-4356-8fca-62df8391c9fb",
    "@type": "https://schema.metadatacenter.org/core/Template",
    "@context": {
      "xsd": "http://www.w3.org/2001/XMLSchema#",
      "pav": "http://purl.org/pav/",
      "bibo": "http://purl.org/ontology/bibo/",
      "oslc": "http://open-services.net/ns/core#",
      "schema": "http://schema.org/",
      "schema:name": {
        "@type": "xsd:string"
      },
      "schema:description": {
        "@type": "xsd:string"
      },
      "pav:createdOn": {
        "@type": "xsd:dateTime"
      },
      "pav:createdBy": {
        "@type": "@id"
      },
      "pav:lastUpdatedOn": {
        "@type": "xsd:dateTime"
      },
      "oslc:modifiedBy": {
        "@type": "@id"
      }
    },
    "type": "object",
    "title": "Template template schema",
    "description": "Template template schema generated by the CEDAR Template Editor 2.6.32-SNAPSHOT",
    "_ui": {
      "pages": [],
      "order": [
        "ABC"
      ],
      "propertyLabels": {
        "ABC": "ABC"
      },
      "propertyDescriptions": {
        "ABC": "Help Text"
      }
    },
    "properties": {
      "@context": {
        "type": "object",
        "properties": {
          "rdfs": {
            "type": "string",
            "format": "uri",
            "enum": [
              "http://www.w3.org/2000/01/rdf-schema#"
            ]
          },
          "xsd": {
            "type": "string",
            "format": "uri",
            "enum": [
              "http://www.w3.org/2001/XMLSchema#"
            ]
          },
          "pav": {
            "type": "string",
            "format": "uri",
            "enum": [
              "http://purl.org/pav/"
            ]
          },
          "schema": {
            "type": "string",
            "format": "uri",
            "enum": [
              "http://schema.org/"
            ]
          },
          "oslc": {
            "type": "string",
            "format": "uri",
            "enum": [
              "http://open-services.net/ns/core#"
            ]
          },
          "skos": {
            "type": "string",
            "format": "uri",
            "enum": [
              "http://www.w3.org/2004/02/skos/core#"
            ]
          },
          "rdfs:label": {
            "type": "object",
            "properties": {
              "@type": {
                "type": "string",
                "enum": [
                  "xsd:string"
                ]
              }
            }
          },
          "schema:isBasedOn": {
            "type": "object",
            "properties": {
              "@type": {
                "type": "string",
                "enum": [
                  "@id"
                ]
              }
            }
          },
          "schema:name": {
            "type": "object",
            "properties": {
              "@type": {
                "type": "string",
                "enum": [
                  "xsd:string"
                ]
              }
            }
          },
          "schema:description": {
            "type": "object",
            "properties": {
              "@type": {
                "type": "string",
                "enum": [
                  "xsd:string"
                ]
              }
            }
          },
          "pav:derivedFrom": {
            "type": "object",
            "properties": {
              "@type": {
                "type": "string",
                "enum": [
                  "@id"
                ]
              }
            }
          },
          "pav:createdOn": {
            "type": "object",
            "properties": {
              "@type": {
                "type": "string",
                "enum": [
                  "xsd:dateTime"
                ]
              }
            }
          },
          "pav:createdBy": {
            "type": "object",
            "properties": {
              "@type": {
                "type": "string",
                "enum": [
                  "@id"
                ]
              }
            }
          },
          "pav:lastUpdatedOn": {
            "type": "object",
            "properties": {
              "@type": {
                "type": "string",
                "enum": [
                  "xsd:dateTime"
                ]
              }
            }
          },
          "oslc:modifiedBy": {
            "type": "object",
            "properties": {
              "@type": {
                "type": "string",
                "enum": [
                  "@id"
                ]
              }
            }
          },
          "skos:notation": {
            "type": "object",
            "properties": {
              "@type": {
                "type": "string",
                "enum": [
                  "xsd:string"
                ]
              }
            }
          },
          "ABC": {
            "enum": [
              "https://schema.metadatacenter.orgx/properties/a4208d82-dca9-4740-b19b-b0f5bd3d903f"
            ]
          }
        },
        "required": [
          "xsd",
          "pav",
          "schema",
          "oslc",
          "schema:isBasedOn",
          "schema:name",
          "schema:description",
          "pav:createdOn",
          "pav:createdBy",
          "pav:lastUpdatedOn",
          "oslc:modifiedBy"
        ],
        "additionalProperties": false
      },
      "@id": {
        "type": [
          "string",
          "null"
        ],
        "format": "uri"
      },
      "@type": {
        "oneOf": [
          {
            "type": "string",
            "format": "uri"
          },
          {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "string",
              "format": "uri"
            },
            "uniqueItems": true
          }
        ]
      },
      "schema:isBasedOn": {
        "type": "string",
        "format": "uri"
      },
      "schema:name": {
        "type": "string",
        "minLength": 1
      },
      "schema:description": {
        "type": "string"
      },
      "pav:derivedFrom": {
        "type": "string",
        "format": "uri"
      },
      "pav:createdOn": {
        "type": [
          "string",
          "null"
        ],
        "format": "date-time"
      },
      "pav:createdBy": {
        "type": [
          "string",
          "null"
        ],
        "format": "uri"
      },
      "pav:lastUpdatedOn": {
        "type": [
          "string",
          "null"
        ],
        "format": "date-time"
      },
      "oslc:modifiedBy": {
        "type": [
          "string",
          "null"
        ],
        "format": "uri"
      },
      "ABC": {
        "@type": "https://schema.metadatacenter.org/core/TemplateField",
        "@context": {
          "xsd": "http://www.w3.org/2001/XMLSchema#",
          "pav": "http://purl.org/pav/",
          "bibo": "http://purl.org/ontology/bibo/",
          "oslc": "http://open-services.net/ns/core#",
          "schema": "http://schema.org/",
          "skos": "http://www.w3.org/2004/02/skos/core#",
          "schema:name": {
            "@type": "xsd:string"
          },
          "schema:description": {
            "@type": "xsd:string"
          },
          "skos:prefLabel": {
            "@type": "xsd:string"
          },
          "skos:altLabel": {
            "@type": "xsd:string"
          },
          "pav:createdOn": {
            "@type": "xsd:dateTime"
          },
          "pav:createdBy": {
            "@type": "@id"
          },
          "pav:lastUpdatedOn": {
            "@type": "xsd:dateTime"
          },
          "oslc:modifiedBy": {
            "@type": "@id"
          }
        },
        "type": "object",
        "title": "ABC field schema",
        "description": "ABC field schema generated by the CEDAR Template Editor 2.6.32-SNAPSHOT",
        "_ui": {
          "inputType": "textfield"
        },
        "_valueConstraints": {
          "requiredValue": false
        },
        "properties": {
          "@type": {
            "oneOf": [
              {
                "type": "string",
                "format": "uri"
              },
              {
                "type": "array",
                "minItems": 1,
                "items": {
                  "type": "string",
                  "format": "uri"
                },
                "uniqueItems": true
              }
            ]
          },
          "@value": {
            "type": [
              "string",
              "null"
            ]
          },
          "rdfs:label": {
            "type": [
              "string",
              "null"
            ]
          }
        },
        "required": [
          "@value"
        ],
        "schema:name": "ABC",
        "schema:description": "Help Text",
        "pav:createdOn": "2023-06-02T14:21:35-07:00",
        "pav:createdBy": "https://metadatacenter.org/users/68d898fd-2b81-492c-b68c-a80c8283fd8a",
        "pav:lastUpdatedOn": "2023-06-02T14:21:35-07:00",
        "oslc:modifiedBy": "https://metadatacenter.org/users/68d898fd-2b81-492c-b68c-a80c8283fd8a",
        "schema:schemaVersion": "1.6.0",
        "additionalProperties": false,
        "@id": "https://repo.metadatacenter.orgx/template-fields/52c249e3-d323-4588-8d52-8d166b60dd94",
        "$schema": "http://json-schema.org/draft-04/schema#"
      }
    },
    "required": [
      "@context",
      "@id",
      "schema:isBasedOn",
      "schema:name",
      "schema:description",
      "pav:createdOn",
      "pav:createdBy",
      "pav:lastUpdatedOn",
      "oslc:modifiedBy",
      "ABC"
    ],
    "schema:name": "Template",
    "schema:description": "",
    "pav:createdOn": "2023-06-02T14:21:35-07:00",
    "pav:createdBy": "https://metadatacenter.org/users/68d898fd-2b81-492c-b68c-a80c8283fd8a",
    "pav:lastUpdatedOn": "2023-06-02T14:21:35-07:00",
    "oslc:modifiedBy": "https://metadatacenter.org/users/68d898fd-2b81-492c-b68c-a80c8283fd8a",
    "schema:schemaVersion": "1.6.0",
    "additionalProperties": false,
    "pav:version": "0.0.1",
    "bibo:status": "bibo:draft",
    "$schema": "http://json-schema.org/draft-04/schema#"
  };

  emptyInstance = EmptyTemplateService.initInstance(this.injectedTemplate);

  constructor() {
  }

  ngOnInit(): void {
  }

}
